#!/usr/bin/env python3

"""Generate adapter properties and validate optional MAX adapter pins."""

from __future__ import annotations

import argparse
import json
import re
import sys
import urllib.parse
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Any, Sequence

from common import (
    EXTENSION_DIR,
    UpdaterError,
    fetch_json,
    fetch_maven_versions,
    normalize_aliases,
    parse_coordinate,
    write_or_check,
)


CATALOG_PATH = Path(__file__).resolve().parent / "adapters.json"
DEFAULT_PROPERTIES = EXTENSION_DIR / "ext.properties"
BEGIN_MARKER = "adapter_catalog_source.private = 1"
END_MARKER = (
    "adapter_catalog_source.label = "
    "MAX adapter properties generated by updater/adapters.py"
)
LEGACY_BEGIN_MARKER = "# BEGIN GENERATED MAX ADAPTER PROPERTIES"
LEGACY_END_MARKER = "# END GENERATED MAX ADAPTER PROPERTIES"
NETWORK_KEY_PATTERN = re.compile(r"^[a-z][a-z0-9_]*$")
SKADNETWORK_KEY_PATTERN = re.compile(r"^[a-z][a-z0-9-]*$")
SKADNETWORK_ID_PATTERN = re.compile(r"^[a-z0-9]{10}\.skadnetwork$")


def _require_string(value: Any, label: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise UpdaterError(f"{label} must be a non-empty string")
    return value


def _require_https(value: Any, label: str) -> str:
    url = _require_string(value, label)
    parsed = urllib.parse.urlparse(url)
    if parsed.scheme != "https" or not parsed.netloc:
        raise UpdaterError(f"{label} must be an HTTPS URL")
    return url


def _require_string_list(value: Any, label: str) -> list[str]:
    if value is None:
        return []
    if (
        not isinstance(value, list)
        or any(not isinstance(item, str) or not item.strip() for item in value)
    ):
        raise UpdaterError(f"{label} must be a list of non-empty strings")
    if len(value) != len(set(value)):
        raise UpdaterError(f"{label} must not contain duplicates")
    return value


def _validate_coordinate(coordinate: str, label: str) -> None:
    group, _, version = parse_coordinate(coordinate)
    if group != "com.applovin.mediation" and label.endswith(".coordinate"):
        raise UpdaterError(f"{label} must use com.applovin.mediation")
    if "+" in version:
        raise UpdaterError(f"{label} must pin an exact version")


def load_adapter_catalog() -> dict[str, Any]:
    try:
        catalog = json.loads(CATALOG_PATH.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise UpdaterError(f"Unable to read {CATALOG_PATH}: {error}") from error
    if not isinstance(catalog, dict) or catalog.get("schema_version") != 1:
        raise UpdaterError(f"{CATALOG_PATH} must use schema_version 1")

    _require_string(catalog.get("catalog_version"), "catalog_version")
    sources = catalog.get("sources")
    if not isinstance(sources, dict) or not sources:
        raise UpdaterError("sources must be a non-empty object")
    for name, url in sources.items():
        _require_https(url, f"sources.{name}")

    android = catalog.get("android")
    ios = catalog.get("ios")
    if not isinstance(android, dict) or not isinstance(ios, dict):
        raise UpdaterError("android and ios must be objects")
    _require_https(android.get("repository"), "android.repository")

    for platform, platform_catalog in (("android", android), ("ios", ios)):
        networks = platform_catalog.get("networks")
        if not isinstance(networks, dict) or not networks:
            raise UpdaterError(f"{platform}.networks must be non-empty")
        for key, network in networks.items():
            if not NETWORK_KEY_PATTERN.fullmatch(key):
                raise UpdaterError(f"invalid {platform} network key: {key!r}")
            if not isinstance(network, dict):
                raise UpdaterError(f"{platform}.networks.{key} must be an object")
            _require_string(
                network.get("display_name"),
                f"{platform}.networks.{key}.display_name",
            )
            if platform == "android":
                coordinate = _require_string(
                    network.get("coordinate"),
                    f"android.networks.{key}.coordinate",
                )
                _validate_coordinate(
                    coordinate, f"android.networks.{key}.coordinate"
                )
                for repository in _require_string_list(
                    network.get("repositories"),
                    f"android.networks.{key}.repositories",
                ):
                    _require_https(
                        repository,
                        f"android.networks.{key}.repositories",
                    )
                for dependency in _require_string_list(
                    network.get("extra_dependencies"),
                    f"android.networks.{key}.extra_dependencies",
                ):
                    _validate_coordinate(
                        dependency,
                        f"android.networks.{key}.extra_dependencies",
                    )
            else:
                _require_string(
                    network.get("pod"), f"ios.networks.{key}.pod"
                )
                version = _require_string(
                    network.get("version"),
                    f"ios.networks.{key}.version",
                )
                if "+" in version:
                    raise UpdaterError(
                        f"ios.networks.{key}.version must be exact"
                    )
                skadnetwork_key = network.get("skadnetwork_key")
                if (
                    skadnetwork_key is not None
                    and (
                        not isinstance(skadnetwork_key, str)
                        or SKADNETWORK_KEY_PATTERN.fullmatch(
                            skadnetwork_key
                        )
                        is None
                    )
                ):
                    raise UpdaterError(
                        f"ios.networks.{key}.skadnetwork_key is invalid"
                    )
                skadnetwork_ids = _require_string_list(
                    network.get("skadnetwork_ids"),
                    f"ios.networks.{key}.skadnetwork_ids",
                )
                if skadnetwork_ids != sorted(skadnetwork_ids):
                    raise UpdaterError(
                        f"ios.networks.{key}.skadnetwork_ids must be sorted"
                    )
                for identifier in skadnetwork_ids:
                    if SKADNETWORK_ID_PATTERN.fullmatch(identifier) is None:
                        raise UpdaterError(
                            f"ios.networks.{key}.skadnetwork_ids contains "
                            f"an invalid identifier: {identifier!r}"
                        )
                if skadnetwork_key is None and skadnetwork_ids:
                    raise UpdaterError(
                        f"ios.networks.{key} has identifiers without a "
                        "generator key"
                    )
                extra_pods = network.get("extra_pods", [])
                if not isinstance(extra_pods, list):
                    raise UpdaterError(
                        f"ios.networks.{key}.extra_pods must be a list"
                    )
                for index, pod in enumerate(extra_pods):
                    if not isinstance(pod, dict):
                        raise UpdaterError(
                            f"ios.networks.{key}.extra_pods[{index}] "
                            "must be an object"
                        )
                    _require_string(
                        pod.get("pod"),
                        f"ios.networks.{key}.extra_pods[{index}].pod",
                    )
                    _require_string(
                        pod.get("version"),
                        f"ios.networks.{key}.extra_pods[{index}].version",
                    )
    return catalog


def render_managed_properties(catalog: dict[str, Any]) -> str:
    lines: list[str] = [
        "adapter_catalog_source.type = string",
        "adapter_catalog_source.default = updater/adapters.json",
        "",
    ]
    android = catalog["android"]["networks"]
    ios = catalog["ios"]["networks"]
    for platform, networks in (("android", android), ("ios", ios)):
        for key in sorted(networks):
            property_name = f"{key}_{platform}"
            lines.extend(
                (
                    f"{property_name}.private = 1",
                    f"{property_name}.type = bool",
                    f"{property_name}.default = 0",
                    (
                        f"{property_name}.label = "
                        f"{networks[key]['display_name']} "
                        f"{'Android' if platform == 'android' else 'iOS'}"
                    ),
                    "",
                )
            )
    if lines[-1] == "":
        lines.pop()
    return "\n".join(lines)


def render_properties(
    current: str, catalog: dict[str, Any]
) -> str:
    block = (
        f"{BEGIN_MARKER}\n"
        f"{render_managed_properties(catalog)}\n"
        f"{END_MARKER}"
    )
    begin_marker = BEGIN_MARKER
    end_marker = END_MARKER
    if LEGACY_BEGIN_MARKER in current or LEGACY_END_MARKER in current:
        begin_marker = LEGACY_BEGIN_MARKER
        end_marker = LEGACY_END_MARKER

    if begin_marker in current or end_marker in current:
        if current.count(begin_marker) != 1 or current.count(end_marker) != 1:
            raise UpdaterError("ext.properties adapter markers are malformed")
        before, remainder = current.split(begin_marker, 1)
        _, after = remainder.split(end_marker, 1)
        content = before.rstrip() + "\n\n" + block + after
    else:
        content = current.rstrip() + "\n\n" + block + "\n"
    return content


def generate_or_check(args: argparse.Namespace, check: bool) -> int:
    catalog = load_adapter_catalog()
    if not args.properties.exists():
        raise UpdaterError(f"Missing extension properties: {args.properties}")
    current = args.properties.read_text(encoding="utf-8")
    generated = render_properties(current, catalog)
    return 0 if write_or_check(args.properties, generated, check) else 1


def _android_metadata_url(
    repository: str, coordinate: str
) -> str:
    group, artifact, _ = parse_coordinate(coordinate)
    return (
        f"{repository.rstrip('/')}/"
        f"{group.replace('.', '/')}/{artifact}/maven-metadata.xml"
    )


def _check_android(
    repository: str, key: str, network: dict[str, Any], timeout: float
) -> tuple[str, bool, str]:
    coordinate = network["coordinate"]
    _, artifact, pinned = parse_coordinate(coordinate)
    release, versions = fetch_maven_versions(
        _android_metadata_url(repository, coordinate), timeout
    )
    if pinned not in versions:
        return key, False, f"missing Android adapter: {coordinate}"
    if release != pinned:
        return (
            key,
            False,
            f"outdated Android adapter: {artifact}:{pinned} "
            f"(latest {release or 'unknown'})",
        )
    return key, True, f"verified Android adapter: {artifact}:{pinned}"


def _check_ios(
    trunk: str, key: str, network: dict[str, Any], timeout: float
) -> tuple[str, bool, str]:
    pod = network["pod"]
    pinned = network["version"]
    encoded = urllib.parse.quote(pod, safe="")
    spec = fetch_json(
        f"{trunk.rstrip('/')}/{encoded}/specs/latest", timeout
    )
    latest = str(spec.get("version", ""))
    if latest != pinned:
        return (
            key,
            False,
            f"outdated iOS adapter: {pod}:{pinned} "
            f"(latest {latest or 'unknown'})",
        )
    return key, True, f"verified iOS adapter: {pod}:{pinned}"


def refresh(args: argparse.Namespace) -> int:
    catalog = load_adapter_catalog()
    android = catalog["android"]
    ios = catalog["ios"]
    trunk = catalog["sources"]["cocoapods_trunk"]
    tasks: list[tuple[str, str, dict[str, Any]]] = []
    tasks.extend(
        ("android", key, network)
        for key, network in android["networks"].items()
    )
    tasks.extend(
        ("ios", key, network)
        for key, network in ios["networks"].items()
    )

    results: list[tuple[str, str, bool, str]] = []
    with ThreadPoolExecutor(max_workers=args.workers) as executor:
        futures = {}
        for platform, key, network in tasks:
            if platform == "android":
                future = executor.submit(
                    _check_android,
                    android["repository"],
                    key,
                    network,
                    args.timeout,
                )
            else:
                future = executor.submit(
                    _check_ios, trunk, key, network, args.timeout
                )
            futures[future] = platform
        for future in as_completed(futures):
            platform = futures[future]
            key, ok, message = future.result()
            results.append((platform, key, ok, message))

    all_ok = True
    for _, _, ok, message in sorted(results):
        print(message, file=sys.stdout if ok else sys.stderr)
        all_ok = all_ok and ok
    if all_ok:
        print("Optional adapter catalog metadata is current.")
        return 0
    print(
        "Adapter validation failed. Reconcile updater/adapters.json with the "
        "official AppLovin guide and adapter repositories.",
        file=sys.stderr,
    )
    return 1


def add_output_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--properties",
        type=Path,
        default=DEFAULT_PROPERTIES,
        help=f"extension properties (default: {DEFAULT_PROPERTIES})",
    )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    commands = parser.add_subparsers(dest="command", required=True)
    add_output_arguments(
        commands.add_parser(
            "generate", help="generate deterministic adapter properties"
        )
    )
    add_output_arguments(
        commands.add_parser(
            "check", help="check generated adapter-property drift"
        )
    )
    refresh_parser = commands.add_parser(
        "refresh", help="validate adapter pins against Maven and CocoaPods"
    )
    refresh_parser.add_argument(
        "--timeout",
        type=float,
        default=30.0,
        help="per-request timeout in seconds (default: 30)",
    )
    refresh_parser.add_argument(
        "--workers",
        type=int,
        default=8,
        help="parallel metadata requests (default: 8)",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    values = normalize_aliases(
        sys.argv[1:] if argv is None else argv,
        ("generate", "check", "refresh"),
    )
    args = build_parser().parse_args(values)
    try:
        if args.command == "generate":
            return generate_or_check(args, False)
        if args.command == "check":
            return generate_or_check(args, True)
        if args.workers <= 0:
            raise UpdaterError("--workers must be greater than zero")
        return refresh(args)
    except UpdaterError as error:
        print(f"error: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
