#!/usr/bin/env python3

"""Generate and validate the AppLovin MAX Android packaging lock."""

from __future__ import annotations

import argparse
import io
import sys
import zipfile
from pathlib import Path
from typing import Any, Sequence

from adapters import load_adapter_catalog
from common import (
    EXTENSION_DIR,
    UpdaterError,
    fetch_bytes,
    fetch_maven_versions,
    load_catalog,
    normalize_aliases,
    sha256_bytes,
    write_or_check,
)


DEFAULT_GRADLE = EXTENSION_DIR / "manifests/android/build.gradle"
DEFAULT_MANIFEST = EXTENSION_DIR / "manifests/android/AndroidManifest.xml"
DEFAULT_PROGUARD = EXTENSION_DIR / "manifests/android/proguard-rules.pro"


def render_gradle(catalog: dict[str, Any]) -> str:
    adapters = load_adapter_catalog()["android"]["networks"]
    sdk = catalog["android"]["sdk"]
    consent = catalog["android"]["consent"]
    networks_url = catalog["scope"]["mediated_networks"]
    lines = [
        "// Generated by updater/android.py from updater/versions.json",
        "// and updater/adapters.json.",
        "// Run `python3 updater/android.py check` in CI.",
        f"// Optional mediated networks: {networks_url}",
        "",
        "repositories {",
        "    google()",
        "    mavenCentral()",
    ]
    for key in sorted(adapters):
        for repository in adapters[key].get("repositories", []):
            condition = f"applovin.{key}_android"
            lines.extend(
                (
                    f"    {{{{#{condition}}}}}",
                    f"    maven {{ url '{repository}' }}",
                    f"    {{{{/{condition}}}}}",
                )
            )
    lines.extend(
        (
            "}",
            "",
            "dependencies {",
            f"    implementation '{sdk['coordinate']}'",
            "    // Required by the MAX consent flow used by the example.",
            f"    implementation '{consent['coordinate']}'",
        )
    )
    for key in sorted(adapters):
        network = adapters[key]
        condition = f"applovin.{key}_android"
        lines.extend(
            (
                "",
                f"    {{{{#{condition}}}}}",
                f"    // {network['display_name']}",
                f"    implementation '{network['coordinate']}'",
            )
        )
        for dependency in network.get("extra_dependencies", []):
            lines.append(f"    implementation '{dependency}'")
        lines.append(f"    {{{{/{condition}}}}}")
    lines.extend(("}", ""))
    return "\n".join(lines)


def render_manifest(catalog: dict[str, Any]) -> str:
    minimum_sdk = catalog["android"]["minimum_sdk"]
    return f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by updater/android.py from updater/versions.json. -->
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="{{{{android.package}}}}">

    <uses-sdk android:minSdkVersion="{minimum_sdk}" />

    <application>
{{{{#applovin.google_android_app_id}}}}
        <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="{{{{applovin.google_android_app_id}}}}" />
{{{{/applovin.google_android_app_id}}}}
    </application>
</manifest>
"""


def render_proguard(catalog: dict[str, Any]) -> str:
    android = catalog["android"]
    max_rules = "\n".join(android["sdk"]["consumer_rules"])
    consent_rules = "\n".join(android["consent"]["consumer_rules"])
    return f"""# Generated by updater/android.py from updater/versions.json.
# AppLovin MAX {android["sdk"]["version"]} consumer rules.

{max_rules}

# Google UMP {android["consent"]["version"]} consumer rules.
# Generated proto fields are accessed reflectively.
{consent_rules}

# Defold resolves this JNI bridge by class and method names.
-keep class com.defold.applovin.MaxDefoldPlugin {{ *; }}
"""


def generate_or_check(args: argparse.Namespace, check: bool) -> int:
    catalog = load_catalog()
    results = (
        write_or_check(args.gradle, render_gradle(catalog), check),
        write_or_check(args.manifest, render_manifest(catalog), check),
        write_or_check(args.proguard, render_proguard(catalog), check),
    )
    return 0 if all(results) else 1


def validate_dependency(
    name: str, dependency: dict[str, Any], timeout: float
) -> bool:
    release, versions = fetch_maven_versions(
        dependency["metadata_url"], timeout
    )
    pinned = dependency["version"]
    if pinned not in versions:
        print(
            f"missing: {dependency['coordinate']} is not published",
            file=sys.stderr,
        )
        return False

    ok = True
    if release != pinned:
        print(
            f"outdated: {name} {pinned} "
            f"(Maven release is {release or 'unknown'})",
            file=sys.stderr,
        )
        ok = False
    else:
        print(f"verified: {dependency['coordinate']} is the Maven release")

    artifact = fetch_bytes(dependency["artifact_url"], timeout)
    actual_sha256 = sha256_bytes(artifact)
    if actual_sha256 != dependency["artifact_sha256"]:
        print(
            f"checksum mismatch: {dependency['artifact_url']}\n"
            f"  expected {dependency['artifact_sha256']}\n"
            f"  actual   {actual_sha256}",
            file=sys.stderr,
        )
        return False
    print(f"verified: {name} artifact SHA-256")

    try:
        with zipfile.ZipFile(io.BytesIO(artifact)) as archive:
            consumer_rules_bytes = archive.read("proguard.txt")
    except (KeyError, zipfile.BadZipFile) as error:
        print(
            f"invalid {name} AAR consumer rules: {error}",
            file=sys.stderr,
        )
        return False
    actual_rules_sha256 = sha256_bytes(consumer_rules_bytes)
    if actual_rules_sha256 != dependency["consumer_rules_sha256"]:
        print(
            f"consumer-rule checksum mismatch in {name} AAR:\n"
            f"  expected {dependency['consumer_rules_sha256']}\n"
            f"  actual   {actual_rules_sha256}",
            file=sys.stderr,
        )
        return False
    try:
        consumer_rules_text = consumer_rules_bytes.decode("utf-8")
    except UnicodeDecodeError as error:
        print(
            f"invalid UTF-8 in {name} AAR consumer rules: {error}",
            file=sys.stderr,
        )
        return False
    active_rules = [
        line.rstrip()
        for line in consumer_rules_text.splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    ]
    if active_rules != dependency["consumer_rules"]:
        print(
            f"active {name} consumer rules differ from the catalog",
            file=sys.stderr,
        )
        return False
    print(f"verified: {name} consumer rules")
    return ok


def refresh(args: argparse.Namespace) -> int:
    catalog = load_catalog()
    android = catalog["android"]
    ok = validate_dependency("AppLovin MAX", android["sdk"], args.timeout)
    ok = (
        validate_dependency(
            "Google UMP consent dependency",
            android["consent"],
            args.timeout,
        )
        and ok
    )
    if ok:
        print("Android catalog metadata and artifacts are current.")
        return 0
    print(
        "Android catalog validation failed. Review official release notes "
        "before explicitly editing updater/versions.json.",
        file=sys.stderr,
    )
    return 1


def add_output_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--gradle",
        type=Path,
        default=DEFAULT_GRADLE,
        help=f"build.gradle output (default: {DEFAULT_GRADLE})",
    )
    parser.add_argument(
        "--manifest",
        type=Path,
        default=DEFAULT_MANIFEST,
        help=f"AndroidManifest.xml output (default: {DEFAULT_MANIFEST})",
    )
    parser.add_argument(
        "--proguard",
        type=Path,
        default=DEFAULT_PROGUARD,
        help=f"extension shrinker rules (default: {DEFAULT_PROGUARD})",
    )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=__doc__,
        epilog=(
            "Compatibility aliases --generate, --check, and --refresh are "
            "also accepted."
        ),
    )
    commands = parser.add_subparsers(dest="command", required=True)

    generate_parser = commands.add_parser(
        "generate", help="generate deterministic Android manifests"
    )
    add_output_arguments(generate_parser)

    check_parser = commands.add_parser(
        "check", help="check generated Android manifest drift"
    )
    add_output_arguments(check_parser)

    refresh_parser = commands.add_parser(
        "refresh",
        help="validate exact pins against live Maven metadata and artifacts",
    )
    refresh_parser.add_argument(
        "--timeout",
        type=float,
        default=30.0,
        help="per-request timeout in seconds (default: 30)",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    values = normalize_aliases(
        sys.argv[1:] if argv is None else argv,
        ("generate", "check", "refresh"),
    )
    args = build_parser().parse_args(values)
    try:
        if args.command == "generate":
            return generate_or_check(args, False)
        if args.command == "check":
            return generate_or_check(args, True)
        return refresh(args)
    except UpdaterError as error:
        print(f"error: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
