#!/usr/bin/env python3

"""Generate, validate, and refresh AppLovin MAX iOS packaging."""

from __future__ import annotations

import argparse
import json
import plistlib
import re
import shutil
import stat
import sys
import tempfile
import urllib.parse
import zipfile
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import date
from pathlib import Path, PurePosixPath
from typing import Any, Sequence

from adapters import (
    CATALOG_PATH as ADAPTER_CATALOG_PATH,
    load_adapter_catalog,
)
from common import (
    CATALOG_PATH,
    EXTENSION_DIR,
    UpdaterError,
    fetch_bytes,
    fetch_json,
    load_catalog,
    normalize_aliases,
    sha256_bytes,
    sha256_file,
    tree_sha256,
    write_or_check,
)


DEFAULT_PODFILE = EXTENSION_DIR / "manifests/ios/Podfile"
DEFAULT_INFO_PLIST = EXTENSION_DIR / "manifests/ios/Info.plist"
DEFAULT_EXT_MANIFEST = EXTENSION_DIR / "ext.manifest"
DEFAULT_RESOURCE_BUNDLE = (
    EXTENSION_DIR / "res/ios/AppLovinSDKResources.bundle"
)
COCOAPODS_TRUNK = "https://trunk.cocoapods.org/api/v1/pods"
SKADNETWORK_ID_PATTERN = re.compile(r"[a-z0-9]{10}\.skadnetwork")
SKADNETWORK_ADAPTER_KEYS = {
    "amazon": "amazon-ad-marketplace",
    "bidmachine": "bidmachine",
    "bigo": "bigoads",
    "chartboost": "chartboost",
    "csj": "csj",
    "dt_exchange": "fyber",
    "google": "google",
    "google_ad_manager": "google-ad-manager",
    "hyprmx": "hyprmx",
    "inmobi": "inmobi",
    "ironsource": "ironsource",
    "liftoff": "vungle",
    "line": "line",
    "maio": "maio",
    "meta": "facebook",
    "mintegral": "mintegral",
    "mobilefuse": "mobilefuse",
    "moloco": "moloco",
    "ogury": "ogury-presage",
    "pangle": "tiktok",
    "pubmatic": "pubmatic",
    "smaato": "smaato",
    "tencent": None,
    "unity_ads": "unityads",
    "verve": "verve",
    "vk": "mytarget",
    "yandex": "yandex",
    "yso": "yso-network",
}
SLICE_SPECIFIC_BUNDLE_INFO_KEYS = {
    "CFBundleSupportedPlatforms",
    "UIRequiredDeviceCapabilities",
}
SLICE_SPECIFIC_BUNDLE_INFO_PREFIXES = ("DTPlatform", "DTSDK")


def render_podfile(catalog: dict[str, Any]) -> str:
    adapters = load_adapter_catalog()["ios"]["networks"]
    ios = catalog["ios"]
    networks_url = catalog["scope"]["mediated_networks"]
    lines = [
        "# Generated by updater/ios.py from updater/versions.json",
        "# and updater/adapters.json.",
        "# Run `python3 updater/ios.py check` in CI.",
        f"# Optional mediated networks: {networks_url}",
        "",
        "source 'https://cdn.cocoapods.org/'",
        "",
        f"platform :ios, '{ios['minimum_version']}'",
        "inhibit_all_warnings!",
        "",
        f"pod '{ios['pod']}', '{ios['version']}'",
    ]
    for key in sorted(adapters):
        network = adapters[key]
        condition = f"applovin.{key}_ios"
        lines.extend(("", f"{{{{#{condition}}}}}", f"# {network['display_name']}"))
        for pod in network.get("extra_pods", []):
            lines.append(f"pod '{pod['pod']}', '{pod['version']}'")
        lines.append(f"pod '{network['pod']}', '{network['version']}'")
        lines.append(f"{{{{/{condition}}}}}")
    lines.append("")
    return "\n".join(lines)


def render_info_plist(catalog: dict[str, Any]) -> str:
    adapters = load_adapter_catalog()["ios"]["networks"]
    skadnetwork_items = [
        (
            "            <dict><key>SKAdNetworkIdentifier</key>"
            f"<string>{identifier}</string></dict>"
        )
        for identifier in catalog["ios"]["skadnetwork_ids"]
    ]
    for key in sorted(adapters):
        identifiers = adapters[key].get("skadnetwork_ids", [])
        if not identifiers:
            continue
        condition = f"applovin.{key}_ios"
        skadnetwork_items.append(f"{{{{#{condition}}}}}")
        skadnetwork_items.extend(
            (
                "            <dict><key>SKAdNetworkIdentifier</key>"
                f"<string>{identifier}</string></dict>"
            )
            for identifier in identifiers
        )
        skadnetwork_items.append(f"{{{{/{condition}}}}}")
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" '
        '"http://www.apple.com/DTDs/PropertyList-1.0.dtd" '
        '[ <!ATTLIST key merge (keep) #IMPLIED> ]>',
        "<!-- Generated by updater/ios.py from updater/versions.json. -->",
        '<plist version="1.0">',
        "    <dict>",
        "        <key merge='keep'>SKAdNetworkItems</key>",
        "        <array>",
        *skadnetwork_items,
        "        </array>",
        "",
        "        <key>NSUserTrackingUsageDescription</key>",
        "        <string>{{applovin.ios_user_tracking_usage_description}}</string>",
        "{{#applovin.google_ios_app_id}}",
        "        <key>GADApplicationIdentifier</key>",
        "        <string>{{applovin.google_ios_app_id}}</string>",
        "{{/applovin.google_ios_app_id}}",
        "    </dict>",
        "</plist>",
        "",
    ]
    return "\n".join(lines)


def render_ext_manifest(catalog: dict[str, Any]) -> str:
    ios = catalog["ios"]
    frameworks = ",\n".join(
        f'                "{framework}"'
        for framework in ios["frameworks"]
    )
    weak_frameworks = ", ".join(
        f'"{framework}"' for framework in ios["weak_frameworks"]
    )
    libraries = ", ".join(f'"{library}"' for library in ios["libraries"])
    compile_flags = ", ".join(
        f'"{flag}"' for flag in ios["compile_flags"]
    )
    return f"""# Generated by updater/ios.py from updater/versions.json.
name: "AppLovinExt"

platforms:
    ios:
        context:
            frameworks: [
{frameworks}
            ]
            weakFrameworks: [{weak_frameworks}]
            libs: [{libraries}]
            flags: [{compile_flags}]
            linkFlags: ["-ObjC", "-Wl,-rpath,/usr/lib/swift", "-Wl,-rpath,@executable_path/Frameworks"]
"""


def validate_resource_bundle(
    bundle: Path, catalog: dict[str, Any], quiet: bool = False
) -> bool:
    ios = catalog["ios"]
    expected = ios["resource_bundle"]
    if not bundle.is_dir():
        print(f"missing resource bundle: {bundle}", file=sys.stderr)
        return False

    actual_tree_sha256, actual_file_count = tree_sha256(bundle)
    ok = True
    if actual_file_count != expected["file_count"]:
        print(
            f"resource file count mismatch: expected "
            f"{expected['file_count']}, found {actual_file_count}",
            file=sys.stderr,
        )
        ok = False
    if actual_tree_sha256 != expected["tree_sha256"]:
        print(
            "resource tree checksum mismatch:\n"
            f"  expected {expected['tree_sha256']}\n"
            f"  actual   {actual_tree_sha256}",
            file=sys.stderr,
        )
        ok = False

    info_path = bundle / "Info.plist"
    try:
        info = plistlib.loads(info_path.read_bytes())
    except (OSError, plistlib.InvalidFileException) as error:
        print(f"invalid resource Info.plist: {error}", file=sys.stderr)
        return False
    if info.get("CFBundleIdentifier") != "com.applovin.sdk.resources":
        print("unexpected AppLovin resource bundle identifier", file=sys.stderr)
        ok = False
    if info.get("MinimumOSVersion") != ios["minimum_version"]:
        print(
            "AppLovin resource bundle minimum OS does not match catalog",
            file=sys.stderr,
        )
        ok = False
    slice_specific_keys = sorted(
        key
        for key in info
        if key in SLICE_SPECIFIC_BUNDLE_INFO_KEYS
        or key.startswith(SLICE_SPECIFIC_BUNDLE_INFO_PREFIXES)
    )
    if slice_specific_keys:
        print(
            "resource Info.plist contains slice-specific keys: "
            f"{', '.join(slice_specific_keys)}",
            file=sys.stderr,
        )
        ok = False
    if (bundle / "_CodeSignature").exists():
        print(
            "resource bundle must not contain an upstream slice signature",
            file=sys.stderr,
        )
        ok = False

    omid_file = bundle / f"omsdk-v{expected['omid_version']}.js"
    if not omid_file.is_file():
        print(f"missing expected OMID resource: {omid_file.name}", file=sys.stderr)
        ok = False
    stale_omid = sorted(
        path.name for path in bundle.glob("omsdk-v*.js") if path != omid_file
    )
    if stale_omid:
        print(
            f"stale OMID resources: {', '.join(stale_omid)}",
            file=sys.stderr,
        )
        ok = False
    if (bundle / "PrivacyInfo.xcprivacy").exists():
        print(
            "PrivacyInfo.xcprivacy must stay in AppLovinSDK.framework, "
            "not in its signed resource bundle",
            file=sys.stderr,
        )
        ok = False

    if ok and not quiet:
        print(
            f"verified: {bundle} "
            f"({actual_file_count} files, OMID {expected['omid_version']})"
        )
    return ok


def generate_or_check(args: argparse.Namespace, check: bool) -> int:
    catalog = load_catalog()
    results = (
        write_or_check(args.podfile, render_podfile(catalog), check),
        write_or_check(args.info_plist, render_info_plist(catalog), check),
        write_or_check(
            args.ext_manifest, render_ext_manifest(catalog), check
        ),
    )
    if check:
        results += (
            validate_resource_bundle(args.resource_bundle, catalog),
        )
        app_root_privacy = args.resource_bundle.parent / "PrivacyInfo.xcprivacy"
        if app_root_privacy.exists():
            print(
                f"unexpected app-root privacy manifest: {app_root_privacy}",
                file=sys.stderr,
            )
            results += (False,)
    return 0 if all(results) else 1


def _podspec_string_list(
    value: Any, label: str
) -> tuple[list[str], bool]:
    if isinstance(value, str):
        return [value], True
    if isinstance(value, list) and all(
        isinstance(item, str) for item in value
    ):
        return value, True
    print(
        f"podspec {label} must be a string or string list",
        file=sys.stderr,
    )
    return [], False


def validate_podspec(
    spec: dict[str, Any], catalog: dict[str, Any]
) -> bool:
    ios = catalog["ios"]
    ok = True
    expected_values = {
        "name": ios["pod"],
        "version": ios["version"],
    }
    for key, expected in expected_values.items():
        if spec.get(key) != expected:
            print(
                f"podspec {key} mismatch: expected {expected!r}, "
                f"found {spec.get(key)!r}",
                file=sys.stderr,
            )
            ok = False
    platforms = spec.get("platforms")
    if (
        not isinstance(platforms, dict)
        or platforms.get("ios") != ios["minimum_version"]
    ):
        print(
            "podspec iOS platform mismatch: expected "
            f"{ios['minimum_version']!r}, found {platforms!r}",
            file=sys.stderr,
        )
        ok = False
    source = spec.get("source")
    source_url = source.get("http") if isinstance(source, dict) else None
    if source_url != ios["archive_url"]:
        print(
            f"podspec archive mismatch: {source_url!r}", file=sys.stderr
        )
        ok = False
    frameworks, valid_frameworks = _podspec_string_list(
        spec.get("frameworks"), "frameworks"
    )
    if not valid_frameworks or frameworks != ios["frameworks"]:
        print("podspec framework list differs from catalog", file=sys.stderr)
        ok = False
    weak_frameworks, valid_weak_frameworks = _podspec_string_list(
        spec.get("weak_frameworks"), "weak_frameworks"
    )
    if (
        not valid_weak_frameworks
        or weak_frameworks != ios["weak_frameworks"]
    ):
        print("podspec weak-framework list differs from catalog", file=sys.stderr)
        ok = False
    libraries, valid_libraries = _podspec_string_list(
        spec.get("libraries"), "libraries"
    )
    if not valid_libraries or libraries != ios["libraries"]:
        print("podspec library list differs from catalog", file=sys.stderr)
        ok = False
    return ok


def parse_skadnetwork_ids(payload: dict[str, Any]) -> list[str]:
    if payload.get("company_name") != "AppLovin":
        raise UpdaterError(
            "Official SKAdNetwork response has an unexpected company"
        )
    entries = payload.get("skadnetwork_ids")
    if not isinstance(entries, list) or not entries:
        raise UpdaterError(
            "Official SKAdNetwork response contains no identifiers"
        )

    identifiers: list[str] = []
    for entry in entries:
        identifier = (
            entry.get("skadnetwork_id")
            if isinstance(entry, dict)
            else None
        )
        if (
            not isinstance(identifier, str)
            or SKADNETWORK_ID_PATTERN.fullmatch(identifier) is None
        ):
            raise UpdaterError(
                "Official SKAdNetwork response contains an invalid entry"
            )
        identifiers.append(identifier)
    if len(identifiers) != len(set(identifiers)):
        raise UpdaterError(
            "Official SKAdNetwork response contains duplicate identifiers"
        )
    return sorted(identifiers)


def fetch_skadnetwork_ids(
    catalog: dict[str, Any], timeout: float
) -> list[str]:
    ios = catalog["ios"]
    payload = fetch_json(ios["skadnetwork_url"], timeout)
    return parse_skadnetwork_ids(payload)


def fetch_adapter_skadnetwork_ids(
    catalog: dict[str, Any],
    core_identifiers: list[str],
    timeout: float,
    workers: int,
) -> dict[str, list[str]]:
    if workers <= 0:
        raise UpdaterError("--workers must be greater than zero")
    url = catalog["ios"]["skadnetwork_url"]
    core = set(core_identifiers)
    results: dict[str, list[str]] = {
        key: []
        for key, generator_key in SKADNETWORK_ADAPTER_KEYS.items()
        if generator_key is None
    }

    def fetch_one(key: str, generator_key: str) -> tuple[str, list[str]]:
        query = urllib.parse.urlencode({"adnetworks": generator_key})
        payload = fetch_json(f"{url}?{query}", timeout)
        combined = parse_skadnetwork_ids(payload)
        return key, sorted(set(combined) - core)

    with ThreadPoolExecutor(max_workers=workers) as executor:
        futures = {
            executor.submit(fetch_one, key, generator_key): key
            for key, generator_key in SKADNETWORK_ADAPTER_KEYS.items()
            if generator_key is not None
        }
        for future in as_completed(futures):
            key, identifiers = future.result()
            results[key] = identifiers
    return results


def fetch_all_skadnetwork_ids(
    catalog: dict[str, Any],
    timeout: float,
    workers: int,
) -> tuple[list[str], dict[str, list[str]]]:
    core = fetch_skadnetwork_ids(catalog, timeout)
    adapters = fetch_adapter_skadnetwork_ids(
        catalog, core, timeout, workers
    )
    return core, adapters


def refresh(args: argparse.Namespace) -> int:
    catalog = load_catalog()
    ios = catalog["ios"]
    encoded_pod = urllib.parse.quote(ios["pod"], safe="")
    latest = fetch_json(
        f"{COCOAPODS_TRUNK}/{encoded_pod}/specs/latest", args.timeout
    )
    latest_version = str(latest.get("version", ""))
    ok = latest_version == ios["version"]
    if ok:
        print(
            f"verified: {ios['pod']} {ios['version']} is the latest "
            "CocoaPods spec"
        )
    else:
        print(
            f"outdated: {ios['pod']} {ios['version']} "
            f"(CocoaPods latest is {latest_version or 'unknown'})",
            file=sys.stderr,
        )

    live_skadnetwork_ids, live_adapter_ids = fetch_all_skadnetwork_ids(
        catalog, args.timeout, args.workers
    )
    if live_skadnetwork_ids == ios["skadnetwork_ids"]:
        print(
            "verified: pinned SKAdNetwork identifiers match AppLovin"
        )
    else:
        added = sorted(
            set(live_skadnetwork_ids) - set(ios["skadnetwork_ids"])
        )
        removed = sorted(
            set(ios["skadnetwork_ids"]) - set(live_skadnetwork_ids)
        )
        print(
            "outdated: pinned SKAdNetwork identifiers differ from AppLovin",
            file=sys.stderr,
        )
        if added:
            print(
                f"  missing ({len(added)}): {', '.join(added)}",
                file=sys.stderr,
            )
        if removed:
            print(
                f"  removed ({len(removed)}): {', '.join(removed)}",
                file=sys.stderr,
            )
        ok = False

    adapter_catalog = load_adapter_catalog()
    pinned_adapter_ids = {
        key: network.get("skadnetwork_ids", [])
        for key, network in adapter_catalog["ios"]["networks"].items()
    }
    if live_adapter_ids == pinned_adapter_ids:
        print(
            "verified: pinned mediated-network SKAdNetwork identifiers "
            "match AppLovin"
        )
    else:
        changed = sorted(
            key
            for key in live_adapter_ids
            if live_adapter_ids[key] != pinned_adapter_ids.get(key, [])
        )
        print(
            "outdated: mediated-network SKAdNetwork identifiers differ "
            f"for: {', '.join(changed)}",
            file=sys.stderr,
        )
        ok = False

    podspec_bytes = fetch_bytes(ios["podspec_url"], args.timeout)
    podspec_sha256 = sha256_bytes(podspec_bytes)
    if podspec_sha256 != ios["podspec_sha256"]:
        print(
            "podspec checksum mismatch:\n"
            f"  expected {ios['podspec_sha256']}\n"
            f"  actual   {podspec_sha256}",
            file=sys.stderr,
        )
        ok = False
    else:
        print("verified: pinned CocoaPods spec SHA-256")
    try:
        podspec = json.loads(podspec_bytes.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as error:
        raise UpdaterError(f"Invalid pinned podspec JSON: {error}") from error
    ok = validate_podspec(podspec, catalog) and ok

    archive_bytes = fetch_bytes(ios["archive_url"], args.timeout)
    archive_sha256 = sha256_bytes(archive_bytes)
    if archive_sha256 != ios["archive_sha256"]:
        print(
            "AppLovin SDK archive checksum mismatch:\n"
            f"  expected {ios['archive_sha256']}\n"
            f"  actual   {archive_sha256}",
            file=sys.stderr,
        )
        ok = False
    else:
        print("verified: pinned AppLovin SDK archive SHA-256")

    if ok:
        print("iOS catalog metadata is current.")
        return 0
    print(
        "iOS catalog validation failed. Review official release notes before "
        "explicitly editing updater/versions.json.",
        file=sys.stderr,
    )
    return 1


def sync_skadnetwork(
    args: argparse.Namespace, generate: bool = True
) -> int:
    catalog = load_catalog()
    ios = catalog["ios"]
    adapter_catalog = load_adapter_catalog()
    adapter_networks = adapter_catalog["ios"]["networks"]
    if set(adapter_networks) != set(SKADNETWORK_ADAPTER_KEYS):
        raise UpdaterError(
            "iOS adapter catalog and SKAdNetwork generator mapping differ"
        )
    live_identifiers, live_adapter_ids = fetch_all_skadnetwork_ids(
        catalog, args.timeout, args.workers
    )
    core_changed = live_identifiers != ios["skadnetwork_ids"]
    adapter_changed = False
    for key, generator_key in SKADNETWORK_ADAPTER_KEYS.items():
        network = adapter_networks[key]
        if (
            "skadnetwork_key" not in network
            or "skadnetwork_ids" not in network
            or network.get("skadnetwork_key") != generator_key
            or network.get("skadnetwork_ids", []) != live_adapter_ids[key]
        ):
            network["skadnetwork_key"] = generator_key
            network["skadnetwork_ids"] = live_adapter_ids[key]
            adapter_changed = True

    if not core_changed and not adapter_changed:
        print("SKAdNetwork identifiers are already current.")
    else:
        ios["skadnetwork_ids"] = live_identifiers
        catalog["catalog_version"] = date.today().isoformat()
        if core_changed:
            write_or_check(
                CATALOG_PATH,
                json.dumps(catalog, indent=2) + "\n",
                False,
            )
        if adapter_changed:
            adapter_catalog["catalog_version"] = date.today().isoformat()
            write_or_check(
                ADAPTER_CATALOG_PATH,
                json.dumps(adapter_catalog, indent=2) + "\n",
                False,
            )
        print(
            f"updated: {len(live_identifiers)} AppLovin and "
            f"{sum(len(value) for value in live_adapter_ids.values())} "
            "mediated-network SKAdNetwork identifiers"
        )
    if generate:
        return generate_or_check(args, False)
    return 0


def update(args: argparse.Namespace) -> int:
    result = sync_skadnetwork(args, generate=False)
    if result != 0:
        return result
    result = sync_resources(args)
    if result != 0:
        return result
    return generate_or_check(args, False)


def _validate_zip_members(archive: zipfile.ZipFile) -> None:
    for member in archive.infolist():
        path = PurePosixPath(member.filename)
        if path.is_absolute() or ".." in path.parts:
            raise UpdaterError(
                f"Unsafe path in AppLovin archive: {member.filename!r}"
            )
        mode = (member.external_attr >> 16) & 0xFFFF
        if stat.S_ISLNK(mode):
            raise UpdaterError(
                f"Symlink is not allowed in AppLovin archive: "
                f"{member.filename!r}"
            )


def _copy_zip_member(
    archive: zipfile.ZipFile, member_name: str, destination: Path
) -> None:
    try:
        member = archive.getinfo(member_name)
    except KeyError as error:
        raise UpdaterError(
            f"Missing required archive entry: {member_name}"
        ) from error
    destination.parent.mkdir(parents=True, exist_ok=True)
    with archive.open(member) as source, destination.open("wb") as output:
        shutil.copyfileobj(source, output)


def _normalize_resource_bundle(bundle: Path) -> None:
    """Remove archive-slice metadata and signatures from resource-only data."""

    info_path = bundle / "Info.plist"
    try:
        info = plistlib.loads(info_path.read_bytes())
    except (OSError, plistlib.InvalidFileException) as error:
        raise UpdaterError(
            f"Invalid resource bundle Info.plist: {error}"
        ) from error
    for key in list(info):
        if (
            key in SLICE_SPECIFIC_BUNDLE_INFO_KEYS
            or key.startswith(SLICE_SPECIFIC_BUNDLE_INFO_PREFIXES)
        ):
            del info[key]
    info_path.write_bytes(
        plistlib.dumps(info, fmt=plistlib.FMT_XML, sort_keys=True)
    )

    signature = bundle / "_CodeSignature"
    if signature.exists():
        if not signature.is_dir():
            raise UpdaterError(
                f"Unexpected resource signature entry: {signature}"
            )
        shutil.rmtree(signature)


def _extract_resource_inputs(
    archive_path: Path,
    stage: Path,
    catalog: dict[str, Any],
    framework_subpath_key: str = "device_framework_subpath",
) -> tuple[Path, Path, Path]:
    ios = catalog["ios"]
    framework_path = PurePosixPath(ios[framework_subpath_key])
    bundle_name = ios["resource_bundle"]["directory"]
    bundle_prefix = (framework_path / bundle_name).as_posix() + "/"
    framework_info_name = (framework_path / "Info.plist").as_posix()
    privacy_name = (framework_path / "PrivacyInfo.xcprivacy").as_posix()
    staged_bundle = stage / bundle_name
    staged_framework_info = stage / "FrameworkInfo.plist"
    staged_privacy = stage / "PrivacyInfo.xcprivacy"

    try:
        archive = zipfile.ZipFile(archive_path)
    except (OSError, zipfile.BadZipFile) as error:
        raise UpdaterError(f"Invalid AppLovin archive: {error}") from error
    with archive:
        _validate_zip_members(archive)
        bundle_members = [
            member
            for member in archive.infolist()
            if member.filename.startswith(bundle_prefix)
            and not member.is_dir()
        ]
        if not bundle_members:
            raise UpdaterError(
                f"No resource files found under {bundle_prefix}"
            )
        for member in bundle_members:
            relative = PurePosixPath(member.filename).relative_to(
                PurePosixPath(bundle_prefix)
            )
            _copy_zip_member(
                archive,
                member.filename,
                staged_bundle.joinpath(*relative.parts),
            )
        _copy_zip_member(
            archive, framework_info_name, staged_framework_info
        )
        _copy_zip_member(archive, privacy_name, staged_privacy)
    _normalize_resource_bundle(staged_bundle)
    return staged_bundle, staged_framework_info, staged_privacy


def _validate_framework_inputs(
    framework_info_path: Path,
    privacy_path: Path,
    catalog: dict[str, Any],
    expected_info_sha256: str | None,
) -> None:
    ios = catalog["ios"]
    if (
        expected_info_sha256 is not None
        and sha256_file(framework_info_path) != expected_info_sha256
    ):
        raise UpdaterError("AppLovin framework Info.plist checksum mismatch")
    try:
        framework_info = plistlib.loads(framework_info_path.read_bytes())
    except plistlib.InvalidFileException as error:
        raise UpdaterError(
            f"Invalid AppLovin framework Info.plist: {error}"
        ) from error
    if (
        framework_info.get("CFBundleIdentifier") != "com.applovin.sdk"
        or framework_info.get("CFBundleShortVersionString") != ios["version"]
    ):
        raise UpdaterError("AppLovin framework metadata does not match pin")

    if sha256_file(privacy_path) != ios["privacy_manifest_sha256"]:
        raise UpdaterError("AppLovin framework privacy checksum mismatch")
    try:
        privacy = plistlib.loads(privacy_path.read_bytes())
    except plistlib.InvalidFileException as error:
        raise UpdaterError(
            f"Invalid AppLovin privacy manifest: {error}"
        ) from error
    accessed_types = privacy.get("NSPrivacyAccessedAPITypes")
    if not isinstance(accessed_types, list) or not accessed_types:
        raise UpdaterError(
            "AppLovin framework privacy manifest has no accessed API reasons"
        )


def _atomic_replace_bundle(staged_bundle: Path, destination: Path) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    backup = destination.with_name(f".{destination.name}.backup")
    if backup.exists():
        raise UpdaterError(f"Stale resource backup blocks update: {backup}")

    had_destination = destination.exists()
    try:
        if had_destination:
            destination.replace(backup)
        staged_bundle.replace(destination)
    except Exception:
        if destination.exists():
            shutil.rmtree(destination)
        if backup.exists():
            backup.replace(destination)
        raise
    else:
        if backup.exists():
            shutil.rmtree(backup)


def sync_resources(args: argparse.Namespace) -> int:
    catalog = load_catalog()
    ios = catalog["ios"]
    archive_path = args.archive
    temporary_archive: tempfile.NamedTemporaryFile[bytes] | None = None
    try:
        if archive_path is None:
            temporary_archive = tempfile.NamedTemporaryFile(
                prefix="applovin-", suffix=".zip", delete=False
            )
            temporary_archive.write(
                fetch_bytes(ios["archive_url"], args.timeout)
            )
            temporary_archive.close()
            archive_path = Path(temporary_archive.name)
        if not archive_path.is_file():
            raise UpdaterError(f"Archive does not exist: {archive_path}")
        try:
            archive_sha256 = sha256_file(archive_path)
        except OSError as error:
            raise UpdaterError(
                f"Unable to read archive {archive_path}: {error}"
            ) from error
        if archive_sha256 != ios["archive_sha256"]:
            raise UpdaterError(
                f"Archive checksum mismatch for {archive_path}"
            )

        with tempfile.TemporaryDirectory(
            prefix="applovin-resources-"
        ) as stage_directory:
            stage = Path(stage_directory)
            (
                device_bundle,
                device_framework_info,
                device_privacy,
            ) = _extract_resource_inputs(
                archive_path, stage / "device", catalog
            )
            (
                simulator_bundle,
                simulator_framework_info,
                simulator_privacy,
            ) = _extract_resource_inputs(
                archive_path,
                stage / "simulator",
                catalog,
                "simulator_framework_subpath",
            )
            for slice_name, staged_bundle in (
                ("device", device_bundle),
                ("simulator", simulator_bundle),
            ):
                if not validate_resource_bundle(
                    staged_bundle, catalog, quiet=True
                ):
                    raise UpdaterError(
                        f"Staged AppLovin {slice_name} resource bundle "
                        "is invalid"
                    )
            device_tree = tree_sha256(device_bundle)
            simulator_tree = tree_sha256(simulator_bundle)
            if device_tree != simulator_tree:
                raise UpdaterError(
                    "Normalized device and simulator resource bundles differ"
                )
            _validate_framework_inputs(
                device_framework_info,
                device_privacy,
                catalog,
                ios["framework_info_sha256"],
            )
            _validate_framework_inputs(
                simulator_framework_info,
                simulator_privacy,
                catalog,
                None,
            )
            _atomic_replace_bundle(device_bundle, args.resource_bundle)
    finally:
        if temporary_archive is not None:
            Path(temporary_archive.name).unlink(missing_ok=True)

    print(
        f"updated: {args.resource_bundle} from verified MAX "
        f"{ios['version']} device/simulator frameworks"
    )
    print(
        "verified: AppLovin framework PrivacyInfo.xcprivacy is present in "
        "the distribution archive (it is intentionally not copied to app root)"
    )
    return 0


def add_output_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--podfile",
        type=Path,
        default=DEFAULT_PODFILE,
        help=f"Podfile output (default: {DEFAULT_PODFILE})",
    )
    parser.add_argument(
        "--info-plist",
        type=Path,
        default=DEFAULT_INFO_PLIST,
        help=f"Info.plist output (default: {DEFAULT_INFO_PLIST})",
    )
    parser.add_argument(
        "--ext-manifest",
        type=Path,
        default=DEFAULT_EXT_MANIFEST,
        help=f"ext.manifest output (default: {DEFAULT_EXT_MANIFEST})",
    )
    parser.add_argument(
        "--resource-bundle",
        type=Path,
        default=DEFAULT_RESOURCE_BUNDLE,
        help=(
            "checked-in AppLovin resource bundle "
            f"(default: {DEFAULT_RESOURCE_BUNDLE})"
        ),
    )


def add_archive_argument(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--archive",
        type=Path,
        help="use an already downloaded official archive",
    )


def add_resource_bundle_argument(
    parser: argparse.ArgumentParser
) -> None:
    parser.add_argument(
        "--resource-bundle",
        type=Path,
        default=DEFAULT_RESOURCE_BUNDLE,
        help=(
            "resource bundle destination "
            f"(default: {DEFAULT_RESOURCE_BUNDLE})"
        ),
    )


def add_timeout_argument(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--timeout",
        type=float,
        default=60.0,
        help="per-request timeout in seconds (default: 60)",
    )


def add_workers_argument(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--workers",
        type=int,
        default=8,
        help="parallel SKAdNetwork requests (default: 8)",
    )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=__doc__,
        epilog=(
            "With no command, the updater synchronizes SKAdNetwork IDs, "
            "resources, and generated manifests. Compatibility aliases "
            "--generate, --check, --refresh, --sync-skadnetwork, and "
            "--sync-resources are also accepted."
        ),
    )
    commands = parser.add_subparsers(dest="command", required=True)

    update_parser = commands.add_parser(
        "update",
        help=(
            "run the normal iOS update: SKAdNetwork IDs, resources, "
            "and generated manifests"
        ),
    )
    add_output_arguments(update_parser)
    add_archive_argument(update_parser)
    add_timeout_argument(update_parser)
    add_workers_argument(update_parser)

    generate_parser = commands.add_parser(
        "generate", help="generate deterministic iOS manifests"
    )
    add_output_arguments(generate_parser)

    check_parser = commands.add_parser(
        "check",
        help="check generated manifests and checked-in resources",
    )
    add_output_arguments(check_parser)

    refresh_parser = commands.add_parser(
        "refresh",
        help="validate the exact pin against live CocoaPods metadata",
    )
    add_timeout_argument(refresh_parser)
    add_workers_argument(refresh_parser)

    skadnetwork_parser = commands.add_parser(
        "sync-skadnetwork",
        help=(
            "update the pinned identifiers from AppLovin and regenerate "
            "iOS manifests"
        ),
    )
    add_output_arguments(skadnetwork_parser)
    add_timeout_argument(skadnetwork_parser)
    add_workers_argument(skadnetwork_parser)

    resources_parser = commands.add_parser(
        "sync-resources",
        help=(
            "verify the official archive and atomically refresh the "
            "checked-in resource bundle"
        ),
    )
    add_archive_argument(resources_parser)
    add_resource_bundle_argument(resources_parser)
    add_timeout_argument(resources_parser)
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    raw_values = list(sys.argv[1:] if argv is None else argv)
    values = normalize_aliases(
        raw_values,
        (
            "update",
            "generate",
            "check",
            "refresh",
            "sync-skadnetwork",
            "sync-resources",
        ),
    )
    if not values:
        values = ["update"]
    args = build_parser().parse_args(values)
    try:
        if args.command == "update":
            return update(args)
        if args.command == "generate":
            return generate_or_check(args, False)
        if args.command == "check":
            return generate_or_check(args, True)
        if args.command == "refresh":
            return refresh(args)
        if args.command == "sync-skadnetwork":
            return sync_skadnetwork(args)
        return sync_resources(args)
    except UpdaterError as error:
        print(f"error: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
