[applovin]
group = Runtime
title = AppLovin
help = Settings for AppLovin MAX extension

ios_user_tracking_usage_description.private = 1
ios_user_tracking_usage_description.type = string
ios_user_tracking_usage_description.label = iOS User Tracking Usage Description
