[applovin]
group = Runtime
title = AppLovin
help = Settings for AppLovin MAX extension

version.default = 2.0.0

demo_sdk_key.type = string
demo_sdk_key.default =
demo_sdk_key.label = Demo SDK Key (example only)

demo_android_interstitial_ad_unit_id.type = string
demo_android_interstitial_ad_unit_id.default =
demo_android_interstitial_ad_unit_id.label = Demo Android Interstitial Ad Unit ID

demo_android_rewarded_ad_unit_id.type = string
demo_android_rewarded_ad_unit_id.default =
demo_android_rewarded_ad_unit_id.label = Demo Android Rewarded Ad Unit ID

demo_android_banner_ad_unit_id.type = string
demo_android_banner_ad_unit_id.default =
demo_android_banner_ad_unit_id.label = Demo Android Banner Ad Unit ID

demo_android_mrec_ad_unit_id.type = string
demo_android_mrec_ad_unit_id.default =
demo_android_mrec_ad_unit_id.label = Demo Android MREC Ad Unit ID

demo_ios_interstitial_ad_unit_id.type = string
demo_ios_interstitial_ad_unit_id.default =
demo_ios_interstitial_ad_unit_id.label = Demo iOS Interstitial Ad Unit ID

demo_ios_rewarded_ad_unit_id.type = string
demo_ios_rewarded_ad_unit_id.default =
demo_ios_rewarded_ad_unit_id.label = Demo iOS Rewarded Ad Unit ID

demo_ios_banner_ad_unit_id.type = string
demo_ios_banner_ad_unit_id.default =
demo_ios_banner_ad_unit_id.label = Demo iOS Banner Ad Unit ID

demo_ios_mrec_ad_unit_id.type = string
demo_ios_mrec_ad_unit_id.default =
demo_ios_mrec_ad_unit_id.label = Demo iOS MREC Ad Unit ID

ios_user_tracking_usage_description.private = 1
ios_user_tracking_usage_description.type = string
ios_user_tracking_usage_description.label = iOS User Tracking Usage Description

google_android_app_id.private = 1
google_android_app_id.type = string
google_android_app_id.default =
google_android_app_id.label = Google Android App ID

google_ios_app_id.private = 1
google_ios_app_id.type = string
google_ios_app_id.default =
google_ios_app_id.label = Google iOS App ID

adapter_catalog_source.private = 1
adapter_catalog_source.type = string
adapter_catalog_source.default = updater/adapters.json

amazon_android.private = 1
amazon_android.type = bool
amazon_android.default = 0
amazon_android.label = Amazon Publisher Services Android

bidmachine_android.private = 1
bidmachine_android.type = bool
bidmachine_android.default = 0
bidmachine_android.label = BidMachine Android

bigo_android.private = 1
bigo_android.type = bool
bigo_android.default = 0
bigo_android.label = BIGO Ads Android

chartboost_android.private = 1
chartboost_android.type = bool
chartboost_android.default = 0
chartboost_android.label = Chartboost Android

dt_exchange_android.private = 1
dt_exchange_android.type = bool
dt_exchange_android.default = 0
dt_exchange_android.label = DT Exchange Android

google_android.private = 1
google_android.type = bool
google_android.default = 0
google_android.label = Google Bidding and Google AdMob Android

google_ad_manager_android.private = 1
google_ad_manager_android.type = bool
google_ad_manager_android.default = 0
google_ad_manager_android.label = Google Ad Manager Android

hyprmx_android.private = 1
hyprmx_android.type = bool
hyprmx_android.default = 0
hyprmx_android.label = HyprMX Android

inmobi_android.private = 1
inmobi_android.type = bool
inmobi_android.default = 0
inmobi_android.label = InMobi Android

ironsource_android.private = 1
ironsource_android.type = bool
ironsource_android.default = 0
ironsource_android.label = ironSource Android

liftoff_android.private = 1
liftoff_android.type = bool
liftoff_android.default = 0
liftoff_android.label = Liftoff Monetize Android

line_android.private = 1
line_android.type = bool
line_android.default = 0
line_android.label = LINE Android

maio_android.private = 1
maio_android.type = bool
maio_android.default = 0
maio_android.label = Maio Android

meta_android.private = 1
meta_android.type = bool
meta_android.default = 0
meta_android.label = Meta Audience Network Android

mintegral_android.private = 1
mintegral_android.type = bool
mintegral_android.default = 0
mintegral_android.label = Mintegral Android

mobilefuse_android.private = 1
mobilefuse_android.type = bool
mobilefuse_android.default = 0
mobilefuse_android.label = MobileFuse Android

moloco_android.private = 1
moloco_android.type = bool
moloco_android.default = 0
moloco_android.label = Moloco Android

ogury_android.private = 1
ogury_android.type = bool
ogury_android.default = 0
ogury_android.label = Ogury Android

pangle_android.private = 1
pangle_android.type = bool
pangle_android.default = 0
pangle_android.label = Pangle Android

pubmatic_android.private = 1
pubmatic_android.type = bool
pubmatic_android.default = 0
pubmatic_android.label = PubMatic Android

smaato_android.private = 1
smaato_android.type = bool
smaato_android.default = 0
smaato_android.label = Smaato Android

unity_ads_android.private = 1
unity_ads_android.type = bool
unity_ads_android.default = 0
unity_ads_android.label = Unity Ads Android

verve_android.private = 1
verve_android.type = bool
verve_android.default = 0
verve_android.label = Verve Android

vk_android.private = 1
vk_android.type = bool
vk_android.default = 0
vk_android.label = VK Ad Network Android

yandex_android.private = 1
yandex_android.type = bool
yandex_android.default = 0
yandex_android.label = Yandex Android

yso_android.private = 1
yso_android.type = bool
yso_android.default = 0
yso_android.label = YSO Network Android

amazon_ios.private = 1
amazon_ios.type = bool
amazon_ios.default = 0
amazon_ios.label = Amazon Publisher Services iOS

bidmachine_ios.private = 1
bidmachine_ios.type = bool
bidmachine_ios.default = 0
bidmachine_ios.label = BidMachine iOS

bigo_ios.private = 1
bigo_ios.type = bool
bigo_ios.default = 0
bigo_ios.label = BIGO Ads iOS

chartboost_ios.private = 1
chartboost_ios.type = bool
chartboost_ios.default = 0
chartboost_ios.label = Chartboost iOS

csj_ios.private = 1
csj_ios.type = bool
csj_ios.default = 0
csj_ios.label = CSJ iOS

dt_exchange_ios.private = 1
dt_exchange_ios.type = bool
dt_exchange_ios.default = 0
dt_exchange_ios.label = DT Exchange iOS

google_ios.private = 1
google_ios.type = bool
google_ios.default = 0
google_ios.label = Google Bidding and Google AdMob iOS

google_ad_manager_ios.private = 1
google_ad_manager_ios.type = bool
google_ad_manager_ios.default = 0
google_ad_manager_ios.label = Google Ad Manager iOS

hyprmx_ios.private = 1
hyprmx_ios.type = bool
hyprmx_ios.default = 0
hyprmx_ios.label = HyprMX iOS

inmobi_ios.private = 1
inmobi_ios.type = bool
inmobi_ios.default = 0
inmobi_ios.label = InMobi iOS

ironsource_ios.private = 1
ironsource_ios.type = bool
ironsource_ios.default = 0
ironsource_ios.label = ironSource iOS

liftoff_ios.private = 1
liftoff_ios.type = bool
liftoff_ios.default = 0
liftoff_ios.label = Liftoff Monetize iOS

line_ios.private = 1
line_ios.type = bool
line_ios.default = 0
line_ios.label = LINE iOS

maio_ios.private = 1
maio_ios.type = bool
maio_ios.default = 0
maio_ios.label = Maio iOS

meta_ios.private = 1
meta_ios.type = bool
meta_ios.default = 0
meta_ios.label = Meta Audience Network iOS

mintegral_ios.private = 1
mintegral_ios.type = bool
mintegral_ios.default = 0
mintegral_ios.label = Mintegral iOS

mobilefuse_ios.private = 1
mobilefuse_ios.type = bool
mobilefuse_ios.default = 0
mobilefuse_ios.label = MobileFuse iOS

moloco_ios.private = 1
moloco_ios.type = bool
moloco_ios.default = 0
moloco_ios.label = Moloco iOS

ogury_ios.private = 1
ogury_ios.type = bool
ogury_ios.default = 0
ogury_ios.label = Ogury iOS

pangle_ios.private = 1
pangle_ios.type = bool
pangle_ios.default = 0
pangle_ios.label = Pangle iOS

pubmatic_ios.private = 1
pubmatic_ios.type = bool
pubmatic_ios.default = 0
pubmatic_ios.label = PubMatic iOS

smaato_ios.private = 1
smaato_ios.type = bool
smaato_ios.default = 0
smaato_ios.label = Smaato iOS

tencent_ios.private = 1
tencent_ios.type = bool
tencent_ios.default = 0
tencent_ios.label = Tencent Ads iOS

unity_ads_ios.private = 1
unity_ads_ios.type = bool
unity_ads_ios.default = 0
unity_ads_ios.label = Unity Ads iOS

verve_ios.private = 1
verve_ios.type = bool
verve_ios.default = 0
verve_ios.label = Verve iOS

vk_ios.private = 1
vk_ios.type = bool
vk_ios.default = 0
vk_ios.label = VK Ad Network iOS

yandex_ios.private = 1
yandex_ios.type = bool
yandex_ios.default = 0
yandex_ios.label = Yandex iOS

yso_ios.private = 1
yso_ios.type = bool
yso_ios.default = 0
yso_ios.label = YSO Network iOS
adapter_catalog_source.label = MAX adapter properties generated by updater/adapters.py
