# Generated by updater/android.py from updater/versions.json.
# AppLovin MAX 13.6.3 consumer rules.

-dontwarn com.applovin.**
-dontwarn androidx.lifecycle.*
-keepattributes SourceFile,LineNumberTable,Signature,InnerClasses,Exceptions,*Annotation*
-keep class com.applovin.** { *; }
-keep class com.iab.omid.library.applovin.** { *; }
-keep class com.google.android.gms.ads.identifier.** { *; }
-keep class com.google.android.gms.appset.** { *; }
-keep class com.google.android.gms.tasks.** { *; }
-keep public class com.google.android.ump.** { public protected *; }

# Google UMP 4.0.0 consumer rules.
# Generated proto fields are accessed reflectively.
-keepclassmembers class * extends com.google.android.gms.internal.consent_sdk.zzqm {
  <fields>;
}

# Defold resolves this JNI bridge by class and method names.
-keep class com.defold.applovin.MaxDefoldPlugin { *; }
